### ISSUE TITLE
`build` compiles `var = IDENTIFIER` to `assignv`, not `assignn`, when `IDENTIFIER` stands for a literal

### ISSUE THREAD

**Issue by SandTAS** [nbudin/agikit#3]
The `build` subcommand compiles an assignment statement, where the right-hand side is a defined identifier that stands for a literal, into the `assignv` command, rather than `assignn`. For example, this code:

```
#define xyz 55
v100 = xyz;
```

compiles to `04 64 37`, which is `assignv(100, 55)`. I expected `03 64 37`, which is `assignn(100, 55)`

If I had to guess, I would say this line is where it happens:
https://github.com/nbudin/agikit/blob/a8c1cc49ddfea86a83aea2cbc7ab56dff3703344/packages/core/src/Scripting/LogicScriptPrimitiveTree.ts#L33

## Steps to reproduce

```
$ npm install @agikit/cli
$ git clone https://github.com/nbudin/agikit-project-template
```

Create a file agikit-project-template/src/logic/100.logic:

```
#define LITERAL   55
#define VARIABLE v55

v100 = 55;
v100 = LITERAL;
v100 = v55;
v100 = VARIABLE;
```

Build the project:

```
$ ./node_modules/.bin/agikit build agikit-project-template/
```

Extract the newly built project:

```
$ ./node_modules/.bin/agikit extract agikit-project-template/build/ temp-extracted
```

Now temp-extracted/src/logic/100.agilogic contains:

```
v100 = 55;
v100 = v55; // bug
v100 = v55;
v100 = v55;
```

**Comment by nbudin** [comment]
Hey @SandTAS - thanks for the detailed bug report!  I'll have a look at this and get back to you as soon as I can.

**Comment by nbudin** [comment]
This is released in version 0.8.3!  (My build and release workflow is still a bit manual and I'm on a new laptop, so if there are any issues with this release, please let me know - I would certainly believe something got messed up in the release process here.)

**Comment by SandTAS** [comment]
I confirm that #4 makes it work the way I expect. Thanks for a nice piece of software.

I see the commit for 0.8.2, but as of 2022-08-23 20:10:22 UTC I only see version 0.8.2 at https://www.npmjs.com/package/@agikit/cli. Version 0.8.2 is what `npm install @agikit/cli` currently installs for me.

Running the cli of 0.8.2 didn't work for me:
```
$ npm install @agikit/cli@0.8.2
$ ./node_modules/.bin/agikit
/usr/bin/env: ‘ts-node-script’: No such file or directory
```
The shebang line in 0.8.2 is different than in 0.8.0:
```
$ npm install @agikit/cli@0.8.0
$ head -n 1 node_modules/.bin/agikit 
#!/usr/bin/env node
$ npm install @agikit/cli@0.8.2
$ head -n 1 node_modules/.bin/agikit 
#!/usr/bin/env ts-node-script
```

I don't know much about NPM packaging so I may be doing something wrong. To make it work, I downgraded @agikit/cli to 0.8.0, while leaving @agikit/core at 0.8.2.

**Comment by nbudin** [comment]
Yay, glad it works for you! 🎉 

Something is definitely going wrong with my build scripts, then.  I think I should spend some time on making the build process run in GitHub Actions so that this kind of thing is less likely to happen when I change laptops.

In the meantime, `npm install -g ts-node` should work around the issue locally.
